### ISSUE TITLE
More functionality

### ISSUE THREAD

**Issue by nolimits4web** [GuillaumeBiton/HackerNews7#11]
As i see the official Hacker News API is pretty limited. What do you think, is it possible to improve app with following features?
* Tab bar on the bottom with the following sections
  * Top stories (as current one)
  * New stories, just added
  * Ask HN
* Search through HN news using API, not just through current top stories

**Comment by GuillaumeBiton** [comment]
search feature enable. user page also. Need to check HN API changes to see what coud be done.
