### ISSUE TITLE
ArtWork proposal

### ISSUE THREAD

**Issue by GuillaumeBiton** [GuillaumeBiton/HackerNews7#22]
Hi,

This is an artwork proposal before sending HN7 to stores.

![icone_hn7_01](https://cloud.githubusercontent.com/assets/729578/5706242/70584f10-9a7f-11e4-92ab-3c713febf563.png)

![icone_hn7_02](https://cloud.githubusercontent.com/assets/729578/5706250/7a21eb5a-9a7f-11e4-9d82-1ab69f43e588.png)

Feel free to choose your favorite one ? if you have a favorite ;)

**Comment by nolimits4web** [comment]
How does it looks like on iOS home screen?:)

**Comment by GuillaumeBiton** [comment]
![img_0232](https://cloud.githubusercontent.com/assets/729578/5755192/c7f9533a-9ca1-11e4-9230-94a6c8a736f3.PNG)

**Comment by nolimits4web** [comment]
Looks nice, but don't you think that it is a bit "heavy"?) the very first icon (the current one) looks more accurate :)

**Comment by GuillaumeBiton** [comment]
ok

**Comment by nolimits4web** [comment]
Why you closed it? What do you decide? I'll try to find some time tomorrow to try design icon too

**Comment by GuillaumeBiton** [comment]
because I was thinking like you but I waited to hear it.

**Comment by nolimits4web** [comment]
What do you think about this one?
![hn7-icon](https://cloud.githubusercontent.com/assets/999588/5873933/13c23edc-a30d-11e4-8a61-2a0d08e095ce.jpg)

**Comment by nolimits4web** [comment]
And OSX icon
![hn7-osx-icon](https://cloud.githubusercontent.com/assets/999588/5874124/fbf77dec-a30e-11e4-9b56-eb5c13e31c6d.jpg)

**Comment by nolimits4web** [comment]
By the way, what is your plans about releasing it in AppStore?
