### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by besherar** [GuillaumeBiton/HackerNews7#32]
successfully builded in phoneGap but it take the same UI in both IOS and Android , should n't take Material in Android?

**Comment by GuillaumeBiton** [comment]
No, in Framework7, you need some tweaks to enable material.

more information on [F7 website](http://www.idangero.us/framework7/tutorials/tips-to-migrate-ios-theme-app-to-material-theme.html#.VkGmqbyzRd0)
