### ISSUE TITLE
Is panel opened?

### ISSUE THREAD

**Issue by krosoftware** [GuillaumeBiton/HackerNews7#34]
Hello
how to check is panel opened (I mean on right (black) panel) or closed?
Thank you.

**Comment by GuillaumeBiton** [comment]
$$('.panel.panel-right.active') !== []

**Comment by krosoftware** [comment]
Hello
thank you but if I use this code (in the getUserInfo function):

    if ($$('.panel.panel-right.active') !== []){
      alert(1);
    }else{
      alert(0);    
    };

I always see 1, even if panel not visible.
Thank you.

**Comment by GuillaumeBiton** [comment]
Since Framework7 [1.5.2](https://github.com/nolimits4web/Framework7/blob/master/CHANGELOG.md#framework7-v152---updated-on-december-17-2016)
You can trigger event on panel:open and panel:close. check doc here : http://framework7.io/docs/side-panels.html

$$('.panel-right').on('panel:opened', function () {
    myApp.alert('Left panel opened!');
});

**Comment by krosoftware** [comment]
Hello
yes I saw that but I still have question:
what if client execute page with full screen (panel is opened by default) and then client resize browser window to smaller size (right panel will be hidden)?
No event will be fired so I have no idea is panel opened/visible or not.

**Comment by GuillaumeBiton** [comment]
ok so you have to check with two conditions : 

1. check if $$(window).width() > 1280px (panel always active)
2. else if .panel-right as .active class

so I would do :
if ($$(window).width() <= 1280px) {
if (!$$('.panel-right').hasClass('active)) {
alert('panel invisible')
}} else {
alert('panel visibe')
}

**Comment by krosoftware** [comment]
Awesome, yes, that's it, thank you so much!
