### ISSUE TITLE
Unable to run this Example.

### ISSUE THREAD

**Issue by jaideepghosh** [GuillaumeBiton/HackerNews7#35]
After installing all the dependencies using `npm install` When I'm trying to run the example, I'm getting the following output :

![framework7 example error](https://user-images.githubusercontent.com/3909648/41215923-1b72b34c-6d70-11e8-9416-1c8d91c98a15.jpg)

Please help me to resolve it.

**Comment by GuillaumeBiton** [comment]
Hi,

It's because it's should be based on framework7 v1.

An update version to framework7 v3 will be available soon
