### ISSUE TITLE
Can't get the HackerNews7 demo to run

### ISSUE THREAD

**Issue by jim-at-miramontes** [GuillaumeBiton/HackerNews7#37]
I've downloaded the HackerNews7 demo (v. 4.1.4, according to package.json), and am having trouble running it under CentOS 6.10 and npm like so:
```
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.8.0',
  icu: '58.2',
  modules: '48',
  napi: '3',
  node: '6.17.1',
  openssl: '1.0.2r',
  uv: '1.16.1',
  v8: '5.1.281.111',
  zlib: '1.2.11' }
```

"npm install" has a few complaints -- joi, too, and hoek are said to have new homes and the code should point to the new ones, and there are a couple of warnings at the very end:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

In any case, I get the following by doing "npm run dev":
```
$ npm run dev

> hackernews7@4.1.4 dev /var/www/html/example/HackerNews7
> cross-env NODE_ENV=development webpack-dev-server --config ./build/webpack.config.js

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /www/
ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: TypeError: Object.entries is not a function
    at generateMetadataForAssets (/var/www/html/example/HackerNews7/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:174:22)
    at getManifestEntriesFromCompilation (/var/www/html/example/HackerNews7/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:235:25)
    at /var/www/html/example/HackerNews7/node_modules/workbox-webpack-plugin/build/inject-manifest.js:96:21
    at next (native)
    at asyncGeneratorStep (/var/www/html/example/HackerNews7/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/var/www/html/example/HackerNews7/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

I've looked around inside the workbox/webpack code, but, tbh, get lost very quickly.  Is there any advice about what might be wrong?  (BTW, if this isn't the right way/place to check into this, please let me know.)  Thanks!

**Comment by GuillaumeBiton** [comment]
It seems that Object.entries is available for node version > 7

I found a polyfill :

```
if (!Object.entries)
   Object.entries = function( obj ){
      var ownProps = Object.keys( obj ),
         i = ownProps.length,
         resArray = new Array(i); // preallocate the Array

      while (i--)
         resArray[i] = [ownProps[i], obj[ownProps[i]]];
      return resArray;
   };
```

Add this to main.js and give it another try.

**Comment by jim-at-miramontes** [comment]
Thanks for the response.  Unfortunately, there is no main.js in the file tree produced by the install process, so I'm not sure where this snippet should go.  I tried putting it in inside HackerNews7/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js , right before the error, and I now get a slightly different error, but still referring to Object:

$ npm run dev

> hackernews7@4.1.4 dev /var/www/html/productionnext-devapp/HackerNews7
> cross-env NODE_ENV=development webpack-dev-server --config ./build/webpack.config.js

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /www/
ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: TypeError: Object.values is not a function
    at getKnownHashesFromAssets (/var/www/html/productionnext-devapp/HackerNews7/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:219:22)
    at getManifestEntriesFromCompilation (/var/www/html/productionnext-devapp/HackerNews7/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:247:67)
    at /var/www/html/productionnext-devapp/HackerNews7/node_modules/workbox-webpack-plugin/build/inject-manifest.js:96:21
    at next (native)
    at asyncGeneratorStep (/var/www/html/productionnext-devapp/HackerNews7/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/var/www/html/productionnext-devapp/HackerNews7/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
⚠ ｢wds｣: Unable to open browser. If you are running in a headless environment, please do not use the --open flag

I also tried some other places, like in build/build.js and src/js/app.js, but no luck.  (I confess that these latter attempts were just unprincipled hacking...)

Anyway, any further thoughts?

Best,
Jim

**Comment by jim-at-miramontes** [comment]
For what it's worth, my current plan is to get my server updated to modern versions of node, gcc, and other things.  That seems like a better long-term use of everybody's time, including yours.  Don't worry about this for now; I'll report back when I know more.

Thanks/best,
Jim

**Comment by GuillaumeBiton** [comment]
OK
